export const allowedSports = new Set([
  "Adventure sports",
  "Air sports",
  "Australian Rules Football",
  "Basketball",
  "Combative sports",
  "Cricket",
  "Cycling",
  "Dancing",
  "Equestrian activities",
  "Fishing",
  "Fitness and gym",
  "Golf",
  "Gymnastics",
  "Hockey",
  "Ice and snow sports",
  "Multidiscipline sports",
  "Netball",
  "Racquet sports",
  "Recreational walking",
  "Roller sports",
  "Rugby",
  "Running, athletics, track & field",
  "Scuba diving and snorkelling",
  "Soccer",
  "Surfing",
  "Swimming and diving",
  "Target and precision",
  "Touch football",
  "Water skiing",
  "Wheeled motor sports",
  "Other team ball sports",
  "Other team bat or stick sports",
  "Other & unspecified football",
  "Other and unspecified sport activity",
  "All sports"
]);

export const allowedAgeGroups = new Set([
  "0-4",
  "5-14",
  "15-24",
  "25-44",
  "45-64",
  "65+",
  "All ages"
]);

export const sportsDropdown = [
  { sport_name: "Australian Rules Football" },
  { sport_name: "Basketball" },
  { sport_name: "Combative sports" },
  { sport_name: "Cricket" },
  { sport_name: "Cycling" },
  { sport_name: "Equestrian activities" },
  { sport_name: "Gymnastics" },
  { sport_name: "Hockey" },
  { sport_name: "Ice and snow sports" },
  { sport_name: "Racquet sports" },
  { sport_name: "Recreational walking" },
  { sport_name: "Roller sports" },
  { sport_name: "Rugby" },
  { sport_name: "Soccer" },
  { sport_name: "Swimming and diving" },
  { sport_name: "Touch football" },
  { sport_name: "Water skiing" },
  { sport_name: "Wheeled motor sports" },
  { sport_name: "Other team bat or stick sports" },
  { sport_name: "Other & unspecified football" },
  { sport_name: "Other and unspecified sport activity" },
  { sport_name: "All sports" }
];

export const ageGroupDropdown = [
  { age_group_label: "0-4" },
  { age_group_label: "5-14" },
  { age_group_label: "15-24" },
  { age_group_label: "25-44" },
  { age_group_label: "45-64" },
  { age_group_label: "65+" },
  { age_group_label: "All ages" }
];