export const allowedSports = new Set([
  "Adventure sports",
  "Air sports",
  "Australian Rules Football",
  "Basketball",
  "Boating sports",
  "Combative sports",
  "Cricket",
  "Cycling",
  "Dancing",
  "Equestrian activities",
  "Fishing",
  "Fitness and gym",
  "Golf",
  "Gymnastics",
  "Hockey",
  "Ice and snow sports",
  "Multidiscipline sports",
  "Netball",
  "Racquet sports",
  "Recreational walking",
  "Roller sports",
  "Rugby",
  "Running, athletics, track & field",
  "Scuba diving and snorkelling",
  "Soccer",
  "Surfing",
  "Swimming and diving",
  "Target and precision",
  "Touch football",
  "Water skiing",
  "Wheeled motor sports",
  "Other team ball sports",
  "Other team bat or stick sports",
  "Other & unspecified football",
  "Other and unspecified sport activity",
  "All sports"
]);

const allowedAgeGroups = new Set([
  "0-4",
  "5-14",
  "15-24",
  "25-44",
  "45-64",
  "65+",
  "All ages"
]);